const translations={
en:{
"nav.home":"Home","nav.doctors":"Doctors","nav.appointments":"Appointments","nav.how":"How it works",
"hero.eyebrow":"SMART HEALTHCARE BOOKING","hero.title":"Find the right doctor. Book in minutes.","hero.text":"Search specialists, compare availability and manage appointments from one simple platform.","hero.cta":"Find doctors","hero.support":"Booking access","hero.specialists":"Specialists","hero.rating":"Average rating","hero.available":"Doctor available","hero.today":"Today at 15:30","hero.confirmed":"Booking confirmed","hero.instant":"Instant confirmation",
"specialties.general":"General Medicine","specialties.cardiology":"Cardiology","specialties.dermatology":"Dermatology","specialties.pediatrics":"Pediatrics",
"doctors.eyebrow":"SPECIALISTS","doctors.title":"Choose a doctor that fits your needs.","doctors.text":"Filter by specialty, availability and experience.","doctors.emptyTitle":"No doctors found","doctors.emptyText":"Try another search or specialty.",
"filter.all":"All","sort.rating":"Top rated","sort.experience":"Most experienced","sort.price":"Lowest price",
"appointments.eyebrow":"YOUR SCHEDULE","appointments.title":"Upcoming appointments","appointments.text":"Appointments booked in this demo are saved locally in your browser.","appointments.summaryLabel":"SUMMARY","appointments.summaryTitle":"Your health schedule","appointments.total":"Total bookings","appointments.next":"Next appointment","appointments.clear":"Clear demo bookings","appointments.empty":"No appointments booked yet.","appointments.booked":"Appointment booked successfully.","appointments.removed":"Appointment removed.","appointments.cleared":"Demo bookings cleared.",
"how.eyebrow":"HOW IT WORKS","how.title":"Three steps from search to appointment.","how.step1Title":"Find a specialist","how.step1Text":"Search by doctor name or medical specialty.","how.step2Title":"Choose a time","how.step2Text":"Select an available appointment slot.","how.step3Title":"Confirm booking","how.step3Text":"Save the appointment and manage it from your schedule.",
"footer.demo":"Healthcare booking demo created for a developer portfolio.","footer.product":"Product","footer.note":"Demo note","footer.noMedical":"No real medical service or consultation is provided.",
"booking.eyebrow":"BOOK APPOINTMENT","booking.name":"Patient name","booking.date":"Date","booking.time":"Time","booking.type":"Consultation type","booking.clinic":"Clinic visit","booking.video":"Video consultation","booking.confirm":"Confirm appointment",
"card.experience":"Experience","card.price":"From","card.available":"Available","card.details":"View details","card.book":"Book","card.years":"years","card.today":"Today",
"modal.about":"About","modal.languages":"Languages","modal.consultation":"Consultation","modal.book":"Book appointment","search.placeholder":"Search doctor or specialty"
},
pt:{
"nav.home":"Início","nav.doctors":"Médicos","nav.appointments":"Consultas","nav.how":"Como funciona",
"hero.eyebrow":"MARCAÇÃO DE CONSULTAS","hero.title":"Encontra o médico certo. Marca em poucos minutos.","hero.text":"Pesquisa especialistas, compara disponibilidade e gere consultas numa plataforma simples.","hero.cta":"Encontrar médicos","hero.support":"Acesso à marcação","hero.specialists":"Especialistas","hero.rating":"Avaliação média","hero.available":"Médico disponível","hero.today":"Hoje às 15:30","hero.confirmed":"Consulta confirmada","hero.instant":"Confirmação imediata",
"specialties.general":"Medicina Geral","specialties.cardiology":"Cardiologia","specialties.dermatology":"Dermatologia","specialties.pediatrics":"Pediatria",
"doctors.eyebrow":"ESPECIALISTAS","doctors.title":"Escolhe um médico adequado às tuas necessidades.","doctors.text":"Filtra por especialidade, disponibilidade e experiência.","doctors.emptyTitle":"Nenhum médico encontrado","doctors.emptyText":"Tenta outra pesquisa ou especialidade.",
"filter.all":"Todos","sort.rating":"Melhor avaliação","sort.experience":"Mais experiente","sort.price":"Menor preço",
"appointments.eyebrow":"TUA AGENDA","appointments.title":"Próximas consultas","appointments.text":"As consultas marcadas nesta demonstração ficam guardadas localmente no navegador.","appointments.summaryLabel":"RESUMO","appointments.summaryTitle":"A tua agenda de saúde","appointments.total":"Total de marcações","appointments.next":"Próxima consulta","appointments.clear":"Limpar marcações demo","appointments.empty":"Ainda não existem consultas marcadas.","appointments.booked":"Consulta marcada com sucesso.","appointments.removed":"Consulta removida.","appointments.cleared":"Marcações de demonstração removidas.",
"how.eyebrow":"COMO FUNCIONA","how.title":"Três passos da pesquisa até à consulta.","how.step1Title":"Encontra um especialista","how.step1Text":"Pesquisa pelo nome do médico ou especialidade.","how.step2Title":"Escolhe um horário","how.step2Text":"Selecciona um horário disponível.","how.step3Title":"Confirma a marcação","how.step3Text":"Guarda a consulta e gere-a a partir da tua agenda.",
"footer.demo":"Demonstração de marcação de consultas criada para portfólio de desenvolvimento.","footer.product":"Produto","footer.note":"Nota da demo","footer.noMedical":"Nenhum serviço ou consulta médica real é fornecido.",
"booking.eyebrow":"MARCAR CONSULTA","booking.name":"Nome do paciente","booking.date":"Data","booking.time":"Hora","booking.type":"Tipo de consulta","booking.clinic":"Consulta presencial","booking.video":"Videochamada","booking.confirm":"Confirmar consulta",
"card.experience":"Experiência","card.price":"Desde","card.available":"Disponível","card.details":"Ver detalhes","card.book":"Marcar","card.years":"anos","card.today":"Hoje",
"modal.about":"Sobre","modal.languages":"Idiomas","modal.consultation":"Consulta","modal.book":"Marcar consulta","search.placeholder":"Pesquisar médico ou especialidade"
}};
const doctors=[
{id:"d1",name:"Dr. Ana Martins",specialty:"general",rating:4.9,reviews:132,experience:11,price:1800,avatar:"ana",languages:"English, Português",bioEN:"General practitioner focused on preventive care, adult consultations and routine follow-up.",bioPT:"Médica de medicina geral com foco em prevenção, consultas de adultos e acompanhamento de rotina."},
{id:"d2",name:"Dr. David Wilson",specialty:"cardiology",rating:4.8,reviews:98,experience:14,price:2800,avatar:"david",languages:"English",bioEN:"Cardiologist with experience in cardiovascular assessment, hypertension and long-term cardiac follow-up.",bioPT:"Cardiologista com experiência em avaliação cardiovascular, hipertensão e acompanhamento cardíaco."},
{id:"d3",name:"Dr. Sofia Ribeiro",specialty:"dermatology",rating:4.9,reviews:145,experience:9,price:2400,avatar:"sofia",languages:"Português, English",bioEN:"Dermatologist working with common skin conditions, acne, hair and nail disorders.",bioPT:"Dermatologista que acompanha problemas comuns da pele, acne, cabelo e unhas."},
{id:"d4",name:"Dr. Michael King",specialty:"pediatrics",rating:4.7,reviews:86,experience:12,price:2200,avatar:"michael",languages:"English",bioEN:"Pediatrician providing child health consultations, growth monitoring and parental guidance.",bioPT:"Pediatra dedicado à saúde infantil, crescimento e orientação aos pais."},
{id:"d5",name:"Dr. Inês Nhampossa",specialty:"general",rating:4.9,reviews:119,experience:8,price:1700,avatar:"ines",languages:"Português, English",bioEN:"General medicine specialist with a practical approach to common symptoms and preventive care.",bioPT:"Especialista em medicina geral com abordagem prática a sintomas comuns e prevenção."},
{id:"d6",name:"Dr. Paulo Mucavele",specialty:"cardiology",rating:4.8,reviews:76,experience:16,price:3000,avatar:"paulo",languages:"Português, English",bioEN:"Cardiologist experienced in risk assessment, blood pressure management and outpatient follow-up.",bioPT:"Cardiologista com experiência em avaliação de risco, controlo da pressão arterial e seguimento ambulatório."}
];
let lang=localStorage.getItem("medibookLang")||"en";
let activeSpecialty="all",search="",sortMode="rating";
let favorites=JSON.parse(localStorage.getItem("medibookFavorites")||"[]");
let appointments=JSON.parse(localStorage.getItem("medibookAppointments")||"[]");
const $=id=>document.getElementById(id);const t=k=>translations[lang][k]??k;const money=n=>new Intl.NumberFormat(lang==="pt"?"pt-MZ":"en-US").format(n)+" MT";
function save(){localStorage.setItem("medibookFavorites",JSON.stringify(favorites));localStorage.setItem("medibookAppointments",JSON.stringify(appointments))}
function setLang(next){lang=next;localStorage.setItem("medibookLang",lang);document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});$("langEN").classList.toggle("active",lang==="en");$("langPT").classList.toggle("active",lang==="pt");$("heroSearch").placeholder=t("search.placeholder");renderDoctors();renderAppointments()}
function specialtyName(s){return t("specialties."+s)}
function filteredDoctors(){let list=doctors.filter(d=>(activeSpecialty==="all"||d.specialty===activeSpecialty)&&`${d.name} ${specialtyName(d.specialty)}`.toLowerCase().includes(search.toLowerCase()));if(sortMode==="rating")list.sort((a,b)=>b.rating-a.rating);if(sortMode==="experience")list.sort((a,b)=>b.experience-a.experience);if(sortMode==="price")list.sort((a,b)=>a.price-b.price);return list}
function renderDoctors(){const list=filteredDoctors();$("doctorGrid").innerHTML=list.map((d,i)=>`<article class="doctor-card" style="animation-delay:${i*.05}s">
<div class="doctor-top"><img class="doctor-avatar" src="assets/doctors/${d.avatar}.svg" alt="${d.name}"><div><h3 class="doctor-name">${d.name}</h3><div class="doctor-specialty">${specialtyName(d.specialty)}</div><div class="rating">★★★★★ <span>${d.rating} · ${d.reviews}</span></div></div></div>
<div class="doctor-info"><div><strong>${d.experience}</strong><span>${t("card.experience")}</span></div><div><strong>${money(d.price)}</strong><span>${t("card.price")}</span></div><div><strong>${t("card.today")}</strong><span>${t("card.available")}</span></div></div>
<div class="doctor-bottom"><div class="doctor-price"><strong>${money(d.price)}</strong><span>${t("modal.consultation")}</span></div><div class="card-actions"><button class="outline-btn heart-btn ${favorites.includes(d.id)?"active":""}" data-fav="${d.id}">${favorites.includes(d.id)?"♥":"♡"}</button><button class="outline-btn" data-details="${d.id}">${t("card.details")}</button><button class="book-btn" data-book="${d.id}">${t("card.book")}</button></div></div></article>`).join("");$("doctorEmpty").classList.toggle("hidden",list.length>0)}
function openDoctor(id){const d=doctors.find(x=>x.id===id);$("doctorModalContent").innerHTML=`<div class="doctor-modal-layout"><div class="doctor-modal-visual"><img src="assets/doctors/${d.avatar}.svg" alt="${d.name}"></div><div class="doctor-modal-copy"><span class="eyebrow">${specialtyName(d.specialty).toUpperCase()}</span><h2>${d.name}</h2><div class="rating">★★★★★ <span>${d.rating} · ${d.reviews}</span></div><p>${lang==="pt"?d.bioPT:d.bioEN}</p><div class="doctor-details"><div><strong>${d.experience} ${t("card.years")}</strong><span>${t("card.experience")}</span></div><div><strong>${d.languages}</strong><span>${t("modal.languages")}</span></div><div><strong>${money(d.price)}</strong><span>${t("modal.consultation")}</span></div></div><button class="primary-btn full" data-book="${d.id}">${t("modal.book")}</button></div></div>`;openModal("doctorModal")}
function startBooking(id){const d=doctors.find(x=>x.id===id);closeModal("doctorModal");$("bookingDoctorId").value=d.id;$("bookingDoctorName").textContent=d.name;const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);$("bookingDate").min=tomorrow.toISOString().split("T")[0];$("bookingDate").value=tomorrow.toISOString().split("T")[0];openModal("bookingModal")}
function renderAppointments(){const list=[...appointments].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));$("appointmentCount").textContent=list.length;$("nextAppointment").textContent=list.length?formatDate(list[0].date)+" · "+list[0].time:"—";$("appointmentList").innerHTML=list.length?list.map((a,i)=>{const d=doctors.find(x=>x.id===a.doctorId);return `<article class="appointment-card" style="animation-delay:${i*.04}s"><img src="assets/doctors/${d.avatar}.svg" alt=""><div><h3>${d.name}</h3><p>${specialtyName(d.specialty)} · ${a.patient} · ${a.type==="video"?t("booking.video"):t("booking.clinic")}</p></div><div class="appointment-date">${formatDate(a.date)}<br>${a.time}</div><button class="appointment-remove" data-remove-appointment="${a.id}">×</button></article>`}).join(""):`<div class="empty-state"><h3>${t("appointments.empty")}</h3></div>`}
function formatDate(date){return new Intl.DateTimeFormat(lang==="pt"?"pt-MZ":"en-GB",{day:"2-digit",month:"short"}).format(new Date(date+"T12:00:00"))}
function openModal(id){$(id).classList.add("open");document.body.classList.add("no-scroll")}function closeModal(id){$(id).classList.remove("open");document.body.classList.remove("no-scroll")}
let toastTimer;function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1900)}
document.addEventListener("click",e=>{const fav=e.target.closest("[data-fav]");if(fav){const id=fav.dataset.fav;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();renderDoctors()}const details=e.target.closest("[data-details]");if(details)openDoctor(details.dataset.details);const book=e.target.closest("[data-book]");if(book)startBooking(book.dataset.book);const rem=e.target.closest("[data-remove-appointment]");if(rem){appointments=appointments.filter(a=>a.id!==Number(rem.dataset.removeAppointment));save();renderAppointments();toast(t("appointments.removed"))}const close=e.target.closest("[data-close]");if(close)closeModal(close.dataset.close)});
document.querySelectorAll(".chip").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));btn.classList.add("active");activeSpecialty=btn.dataset.filter;renderDoctors()}));
document.querySelectorAll("[data-specialty]").forEach(btn=>btn.addEventListener("click",()=>{activeSpecialty=btn.dataset.specialty;document.querySelectorAll(".chip").forEach(x=>x.classList.toggle("active",x.dataset.filter===activeSpecialty));renderDoctors();document.getElementById("doctors").scrollIntoView({behavior:"smooth"})}));
$("sortDoctors").addEventListener("change",e=>{sortMode=e.target.value;renderDoctors()});$("heroSearch").addEventListener("input",e=>{search=e.target.value;renderDoctors()});$("heroSpecialty").addEventListener("change",e=>{activeSpecialty=e.target.value;renderDoctors()});
$("bookingForm").addEventListener("submit",e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());appointments.push({id:Date.now(),doctorId:data.doctorId,patient:data.patient,date:data.date,time:data.time,type:data.type});save();renderAppointments();e.target.reset();closeModal("bookingModal");toast(t("appointments.booked"));document.getElementById("appointments").scrollIntoView({behavior:"smooth"})});
$("clearAppointments").addEventListener("click",()=>{appointments=[];save();renderAppointments();toast(t("appointments.cleared"))});
$("langEN").addEventListener("click",()=>setLang("en"));$("langPT").addEventListener("click",()=>setLang("pt"));$("themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("medibookTheme",document.body.classList.contains("dark")?"dark":"light")});if(localStorage.getItem("medibookTheme")==="dark")document.body.classList.add("dark");
$("mobileMenu").addEventListener("click",()=>$("mobileNav").classList.toggle("open"));document.querySelectorAll(".mobile-nav a").forEach(a=>a.addEventListener("click",()=>$("mobileNav").classList.remove("open")));
document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal("doctorModal");closeModal("bookingModal")}});
$("year").textContent=new Date().getFullYear();setLang(lang);renderDoctors();renderAppointments();window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),350));
